project:
  type: website

website:
  title: "Open Science Notes"
  navbar:
    logo: opensciencenotes.svg
    logo-alt: "OpenScienceNotes Logo"
    left:
      - href: index.qmd
        text: Home
      - text: "Genetics"
        menu:
          - href: genetics/01-intro-to-genetics.qmd
            text: "Introduction to Genetics"
          - href: genetics/02-mendelian-inheritance.qmd
            text: "Mendelian Inheritance"
      - href: biology/index.qmd
        text: Biology
      - href: microbiology/index.qmd
        text: Microbiology
      - href: posts/index.qmd
        text: Blog
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css